# Generated by Django 4.2.16 on 2026-05-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_floor',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
