# Generated by Django 4.2.7 on 2026-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_slot',
            field=models.CharField(blank=True, help_text='Franja horaria preferida: manana / tarde', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_type',
            field=models.CharField(choices=[('particular', 'Particular'), ('residencia', 'Residencia geriátrica'), ('institucion', 'Institución / Clínica')], default='particular', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('preparing', 'Preparando'), ('shipped', 'Enviado'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='orders_orde_user_id_a87c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
    ]
