# Generated by Django 4.2.7 on 2026-05-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'size', 'title'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('aposito_incontinencia', 'Apósito Incontinencia'), ('panal_recto', 'Pañal Recto'), ('panal_elastizado', 'Pañal Elastizado'), ('ropa_interior', 'Ropa Interior'), ('accesorios', 'Accesorios'), ('algodon', 'Algodón'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.FloatField(blank=True, help_text='Alto en cm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.FloatField(blank=True, help_text='Largo en cm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_box',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Unidades por bulto', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.PositiveIntegerField(blank=True, help_text='Peso en gramos', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.FloatField(blank=True, help_text='Ancho en cm', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Unidades por paquete (pack)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('CH', 'Chico'), ('MED', 'Mediano'), ('GDE', 'Grande'), ('EX_GDE', 'Extra Grande'), ('EX_EX_GDE', 'Extra Extra Grande'), ('P/M', 'Pequeño/Mediano'), ('G/EG', 'Grande/Extra Grande'), ('UNICO', 'Único'), ('T1', 'Talle 1'), ('T2', 'Talle 2'), ('T3', 'Talle 3'), ('T4', 'Talle 4'), ('1_PLAZA', '1 Plaza'), ('2_PLAZAS', '2 Plazas')], default='UNICO', max_length=20),
        ),
    ]
