# Generated by Django 4.2.7 on 2026-06-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_daily_units',
            field=models.FloatField(blank=True, help_text='Consumo diario promedio (ej: 4 pañales/día)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='for_adult',
            field=models.BooleanField(default=True, help_text='Apto adultos'),
        ),
        migrations.AddField(
            model_name='product',
            name='for_child',
            field=models.BooleanField(default=False, help_text='Apto infantil / juvenil'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_nocturnal',
            field=models.BooleanField(default=False, help_text='Uso nocturno'),
        ),
        migrations.AddField(
            model_name='product',
            name='mobility_reduced',
            field=models.BooleanField(default=False, help_text='Apto movilidad reducida'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Ej: clasico, basico, elastizado', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('panal_basico', 'Pañal Básico'), ('panal_clasico', 'Pañal Clásico'), ('panal_elastizado', 'Pañal Elastizado'), ('panal_juvenil', 'Pañal Juvenil'), ('aposito_incontinencia', 'Apósito Incontinencia'), ('ropa_interior', 'Ropa Interior'), ('donna_fem', 'Donna Fem'), ('accesorios', 'Accesorios'), ('algodon', 'Algodón'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
    ]
