# Generated by Django 6.0.5 on 2026-05-29 20:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ship_date', models.DateField(unique=True)),
                ('cutoff_date', models.DateField()),
                ('cycle_day', models.IntegerField(choices=[(1, 'Día 1'), (15, 'Día 15')])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ciclo de envío',
                'verbose_name_plural': 'Ciclos de envío',
                'ordering': ['ship_date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('postal_codes', models.JSONField(blank=True, default=list)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_days', models.PositiveIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona de envío',
                'verbose_name_plural': 'Zonas de envío',
                'ordering': ['city_name'],
            },
        ),
    ]
