# Generated by Django 4.2.7 on 2026-06-05 01:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_code_order_discount_amount_and_more'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndreaniShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('label_url', models.URLField(blank=True, help_text='URL de etiqueta PDF generada por Andreani')),
                ('service_type', models.CharField(blank=True, help_text='Ej: Andreani A Domicilio', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de creación'), ('created', 'Creado en Andreani'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('failed', 'Fallido / No entregado')], default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Respuesta cruda de Andreani API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andreani_shipment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Envío Andreani',
                'verbose_name_plural': 'Envíos Andreani',
            },
        ),
    ]
