# Generated by Django 4.2.7 on 2026-06-05 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_coupon_code_order_discount_amount_and_more'),
        ('products', '0004_product_default_daily_units_product_for_adult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Vacío = usos ilimitados', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Si está asignado a un usuario, es de uso exclusivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
            },
        ),
        migrations.CreateModel(
            name='RepurchaseReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('reminder', 'Recordatorio de stock'), ('promo', 'Promoción descuento'), ('reorder', 'Invitación a recompra'), ('review', 'Solicitud de reseña')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('converted', 'Convertido en compra'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio de recompra',
                'verbose_name_plural': 'Recordatorios de recompra',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='crm_repurch_status_534899_idx'), models.Index(fields=['user', 'product'], name='crm_repurch_user_id_5543cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_units', models.FloatField(help_text='Unidades físicas consumidas por día (ej: 4)')),
                ('source', models.CharField(choices=[('onboarding', 'Cuestionario inicial'), ('calculated', 'Calculado por historial'), ('manual', 'Ingresado manualmente')], default='onboarding', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de consumo',
                'verbose_name_plural': 'Perfiles de consumo',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
